default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  port: 5432

development:
  <<: *default
  host: localhost
  database: open_street_map_dev
  username: postgres
  password: cisin123

test:
  <<: *default
  host: localhost
  database: open_street_map_test
  username: postgres
  password: cisin123

production:
  <<: *default
  host: localhost
  database: open_street_map_production
  username: postgres
  password: cisin123

